add_test([=[DataFormatTest.EnumValues]=]  /home/runner/work/edfio/edfio/_codeql_build_dir/tests/unit/test_data_format [==[--gtest_filter=DataFormatTest.EnumValues]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataFormatTest.EnumValues]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/edfio/edfio/tests/unit SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test([=[DataFormatTest.IsPlusFunction]=]  /home/runner/work/edfio/edfio/_codeql_build_dir/tests/unit/test_data_format [==[--gtest_filter=DataFormatTest.IsPlusFunction]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataFormatTest.IsPlusFunction]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/edfio/edfio/tests/unit SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test([=[DataFormatTest.IsEdfFunction]=]  /home/runner/work/edfio/edfio/_codeql_build_dir/tests/unit/test_data_format [==[--gtest_filter=DataFormatTest.IsEdfFunction]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataFormatTest.IsEdfFunction]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/edfio/edfio/tests/unit SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test([=[DataFormatTest.IsBdfFunction]=]  /home/runner/work/edfio/edfio/_codeql_build_dir/tests/unit/test_data_format [==[--gtest_filter=DataFormatTest.IsBdfFunction]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataFormatTest.IsBdfFunction]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/edfio/edfio/tests/unit SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test([=[DataFormatTest.GetSampleBytesFunction]=]  /home/runner/work/edfio/edfio/_codeql_build_dir/tests/unit/test_data_format [==[--gtest_filter=DataFormatTest.GetSampleBytesFunction]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataFormatTest.GetSampleBytesFunction]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/edfio/edfio/tests/unit SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
set(  test_data_format_TESTS DataFormatTest.EnumValues DataFormatTest.IsPlusFunction DataFormatTest.IsEdfFunction DataFormatTest.IsBdfFunction DataFormatTest.GetSampleBytesFunction)
