if(EXISTS "/home/runner/work/edfio/edfio/_codeql_build_dir/tests/integration/test_edf_read[1]_tests.cmake")
  include("/home/runner/work/edfio/edfio/_codeql_build_dir/tests/integration/test_edf_read[1]_tests.cmake")
else()
  add_test(test_edf_read_NOT_BUILT test_edf_read_NOT_BUILT)
endif()
