add_test([=[EdfReadTest.SampleFileExists]=]  /home/runner/work/edfio/edfio/_codeql_build_dir/tests/integration/test_edf_read [==[--gtest_filter=EdfReadTest.SampleFileExists]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[EdfReadTest.SampleFileExists]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/edfio/edfio SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS integration)
add_test([=[EdfReadTest.CanOpenAndReadHeader]=]  /home/runner/work/edfio/edfio/_codeql_build_dir/tests/integration/test_edf_read [==[--gtest_filter=EdfReadTest.CanOpenAndReadHeader]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[EdfReadTest.CanOpenAndReadHeader]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/edfio/edfio SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS integration)
add_test([=[EdfReadTest.DataFormatEnumAvailable]=]  /home/runner/work/edfio/edfio/_codeql_build_dir/tests/integration/test_edf_read [==[--gtest_filter=EdfReadTest.DataFormatEnumAvailable]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[EdfReadTest.DataFormatEnumAvailable]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/edfio/edfio SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS integration)
add_test([=[EdfReadTest.HeaderStructuresAvailable]=]  /home/runner/work/edfio/edfio/_codeql_build_dir/tests/integration/test_edf_read [==[--gtest_filter=EdfReadTest.HeaderStructuresAvailable]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[EdfReadTest.HeaderStructuresAvailable]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/edfio/edfio SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS integration)
set(  test_edf_read_TESTS EdfReadTest.SampleFileExists EdfReadTest.CanOpenAndReadHeader EdfReadTest.DataFormatEnumAvailable EdfReadTest.HeaderStructuresAvailable)
